version: "3.8"
services:
  harvey-ui:
    build: .
    restart: always
    networks:
      - traefik
      - harvey-ui
    labels:
      - traefik.enable=true
    env_file:
      - src/.env
    # depends_on:
    #   - harvey-ui-db
    # harvey-ui-db:
    #   image: 'mariadb:10.8.2'
    #   restart: always
    #   volumes:
    #     - database-data:/var/lib/mysql
    #   env_file:
    #     - database.env
    #   networks:
    #     - harvey-ui

networks:
  traefik:
    name: traefik
  harvey-ui:
    name: harvey-ui
