services:
  harvey-ui:
    labels:
      - 'traefik.http.routers.harvey-ui.rule=Host(`harvey.localhost`)'
    depends_on:
      harvey-ui-db:
        condition: service_started
    volumes:
      - ./src:/var/www/html
