version: "3.8"
services:
  harvey-ui:
    deploy:
      replicas: 2
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - traefik.frontend.rule=Host:harvey.justinpaulhammond.com,www.harvey.justinpaulhammond.com
    # TODO: Do we use a named volume here or backup this folder somewhere?
    volumes:
      - ./src/storage:/var/www/html/storage
  # The `harvey-ui-db` and `harvey-ui-db-replica` containers will automatically restart on a failure, no custom healthcheck needed
