services:
  harvey-ui:
    build:
      args:
        PROD: true
    deploy:
      replicas: 2
    mem_limit: '512m'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost']
      start_period: 10s
      start_interval: 2s
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - 'traefik.http.routers.harvey-ui.rule=Host(`harvey.justinpaulhammond.com`, `www.harvey.justinpaulhammond.com`)'
      - 'traefik.http.routers.harvey-ui.tls=true'
      - 'traefik.http.routers.harvey-ui.tls.certresolver=letsencrypt'
    depends_on:
      harvey-ui-db:
        condition: service_healthy
    volumes:
      - ./src/storage:/var/www/html/storage
  harvey-ui-db:
    mem_limit: '768m'
    healthcheck:
      test: ['CMD', 'mariadb', '-u${MARIADB_USER}', '-p${MARIADB_PASSWORD}', '-e', 'show databases;']
      # Need to account for upgrade times at startup
      start_period: 30s
      start_interval: 2s
      interval: 30s
      timeout: 10s
      retries: 3
