services:
  harvey-ui:
    build: .
    restart: always
    networks:
      - traefik
      - harvey-ui
    labels:
      - traefik.enable=true
    env_file:
      - src/.env
  harvey-ui-db:
    image: 'mariadb:10.10.3'
    restart: always
    volumes:
      - database-data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - harvey-ui

volumes:
  database-data:
    driver: local

networks:
  traefik:
    name: traefik
    external: true
  harvey-ui:
    name: harvey-ui
