services:
  harvey-ui:
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.50"
          memory: "512M"
        reservations:
          cpus: "0.25"
          memory: "128M"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 10s
      timeout: 10s
      retries: 3
    labels:
      - "traefik.http.routers.harvey-ui.rule=Host(`harvey.justinpaulhammond.com`, `www.harvey.justinpaulhammond.com`)"
      - "traefik.http.routers.harvey-ui.tls=true"
      - "traefik.http.routers.harvey-ui.tls.certresolver=letsencrypt"
    volumes:
      - ./src/storage:/var/www/html/storage
  harvey-ui-db:
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "512M"
        reservations:
          cpus: "0.25"
          memory: "128M"
    healthcheck:
      test: ["CMD", "mysql", "-u${MARIADB_USER}", "-p${MARIADB_PASSWORD}", "-e", "show databases;"]
      interval: 10s
      timeout: 10s
      retries: 3
