name: build

on: [push, pull_request]

jobs:
  sh-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Run sh-checker
        uses: luizm/action-sh-checker@master
        env:
          SHFMT_OPTS: -i 4 -d
  deploy:
    needs: ["sh-checker"]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Harvey
        if: github.ref == 'refs/heads/main'
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_type: "json-extended"
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          data: '{ "pipeline": "deploy", "prod_compose": true, "healthcheck": ["harvey-ui-1", "harvey-ui-2"] }'
